### ISSUE TITLE
cd command doesnt work for some directories

### ISSUE THREAD

**Issue by montycheese** [jtumale1/FTPClientServer#2]
cd doesn't seem to work for certain directories. Try cd /var cd /usr

**Comment by montycheese** [comment]
Found out it is okay that we can't access certain directories due to file permissions.

**Comment by montycheese** [comment]
Problem w/ Cd we saw in class.

**Comment by mreinerh** [comment]
Shoot, ill check the cd command during class tomorrow. It doesn't look like the method but i will definitely get on this.

EDIT: took out a curse word lawlz

**Comment by montycheese** [comment]
fixed
